Challenge flows
Aleechetorres/cypress-training pull request #7
Opened 2023-10-02 15:44 UTC by Aleechetorres

All instructions in step 8 "Challenge Flows" were carried out

A solution to the blockage is given with the suggestion of @abdulflorez

2023-10-02 16:33 UTC, DanielCalleCO requested changes

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Borra esta línea comentada por favor.

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Borra este comment

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Borra el comment

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Borrar

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(2000);
Delete this

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(1500);
Delete

2023-10-02 16:33 UTC, DanielCalleCO commented on cypress/e2e/google.cy.ts
> +    //cy.wait(2000);
Delete

2023-10-02 16:48 UTC, Aleechetorres commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Hecho dani!

2023-10-02 16:59 UTC, DanielCalleCO approved these changes

2023-10-02 17:05 UTC, Aleechetorres commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Hecho dani!

2023-10-02 17:05 UTC, Aleechetorres commented on cypress/e2e/google.cy.ts
> +    //cy.wait(500);
Hecho dani!

2023-10-02 17:05 UTC, Aleechetorres commented on cypress/e2e/google.cy.ts
> +    //cy.wait(1500);
Hecho dani!

2023-10-02 17:05 UTC, Aleechetorres commented on cypress/e2e/google.cy.ts
> +    //cy.wait(2000);
Hecho dani!

2023-10-02 17:05 UTC, merged

2023-10-03 15:13 UTC, Aleechetorres commented on cypress/e2e/google.cy.ts
> +    //cy.wait(2000);
hecho!